server:
  port: 3366 #服务端口号
spring:
  ################################################## JDBC 通用配置  ##########################################
  datasource:
    username: root       #数据库登陆用户名
    password: 123456        #数据库登陆密码
    url: jdbc:mysql://localhost:3306/tb_database?characterEncoding=UTF8&autoReconnect=true&useSSL=false       #数据库url
    driver-class-name: com.mysql.jdbc.Driver                  #数据库驱动

############################### 不检查 spring.config.import=configserver:##################
#  cloud:
#    config:
#      enabled: false
###################################### MyBatis 配置 ######################################
mybatis:
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true

